"""Change unique constraint to composite on project and table_name

Revision ID: dff8fbe5ad03
Revises: d11444eafed9
Create Date: 2024-05-16 16:49:42.141697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff8fbe5ad03'
down_revision = 'd11444eafed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_ids', schema=None) as batch_op:
        batch_op.drop_constraint('table_ids_table_name_key', type_='unique')
        batch_op.create_unique_constraint('unique_project_table', ['project', 'table_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table_ids', schema=None) as batch_op:
        batch_op.drop_constraint('unique_project_table', type_='unique')
        batch_op.create_unique_constraint('table_ids_table_name_key', ['table_name'])

    # ### end Alembic commands ###
